/**
 * Open Api Specification
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FinancialFormDto { 
    occupation?: string;
    'name-of-employer'?: string;
    wealth?: number;
    'yearly-income'?: number;
}

