/**
 * Open Api Specification
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonaFormDto { 
    first_name?: string;
    second_name?: string;
    birthday?: string;
    civil_status?: string;
    number_of_kids?: number;
}

