/**
 * Open Api Specification
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonaFormDto { 
    'first-name'?: string;
    'second-name'?: string;
    birthday?: string;
    'civil-status'?: string;
    'number-of-kids'?: number;
}

