/**
 * Open Api Specification
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RealEstateOverviewDto { 
    id?: string;
    name?: string;
    description?: string;
    address?: string;
    cost?: number;
}

